services:
  - type: web
    name: laravel-portfolio
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: REDIRECT_HTTPS
        value: "true"
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: RUN_MIGRATIONS
        value: "false"
      - key: RUN_SEEDERS
        value: "false"
      - key: APP_KEY
        generateValue: true
